local emit_classes = {
  ["emit-source-r"] = true,
  ["emit-source-py"] = true,
  ["emit-source-jl"] = true,
  ["emit-source-julia"] = true,
  ["emit-test-r"] = true,
  ["emit-test-py"] = true,
  ["emit-test-jl"] = true,
  ["emit-test-julia"] = true,
  ["emit-script-sh"] = true,
  ["emit-config-yaml"] = true,
  ["emit-config-json"] = true,
  ["emit-config-toml"] = true,
  ["emit-project-root"] = true,
  ["emit-generic"] = true
}

local template_vars = {}
local debug_enabled = os.getenv("QUARTO_EMIT_DEBUG") == "1"

local function log_debug(message)
  if debug_enabled then
    quarto.log.output("[quarto-emit][debug] " .. message)
  end
end

local function stringify(value)
  return pandoc.utils.stringify(value)
end

local function set_template_var(key, value)
  if key == nil or key == "" or value == nil or value == "" then
    return
  end

  template_vars[key] = value
  log_debug("template var " .. key .. "=" .. value)
end

local function register_template_path(parts, value)
  if value == nil or value == "" then
    return
  end

  local dotted = table.concat(parts, ".")
  local underscored = table.concat(parts, "_"):gsub("[^%w_]", "_")

  set_template_var(dotted, value)
  set_template_var(underscored, value)
  set_template_var("emit." .. dotted, value)
end

local function env_name_for_parts(parts)
  return "QUARTO_EMIT_" .. table.concat(parts, "_"):gsub("[^%w_]", "_"):upper()
end

local function apply_env_override(parts)
  local env_name = env_name_for_parts(parts)
  local value = os.getenv(env_name)
  if value ~= nil and value ~= "" then
    register_template_path(parts, value)
    log_debug("env override " .. env_name .. "=" .. value)
  end
end

local function meta_string(path)
  local value = quarto.metadata.get(path)
  if value == nil then
    return nil
  end
  return stringify(value)
end

local function register_metadata_path(parts, ...)
  local value = nil

  for i = 1, select("#", ...) do
    local path = select(i, ...)
    value = meta_string(path)
    if value ~= nil then
      break
    end
  end

  if value ~= nil then
    register_template_path(parts, value)
  else
    log_debug("metadata field " .. select(1, ...) .. " is nil")
  end
end

local function load_emit_vars()
  template_vars = {}

  register_metadata_path({ "project_root" }, "emit.project_root")
  register_metadata_path({ "project_name" }, "emit.project_name")

  register_metadata_path({ "source", "r" }, "emit.source.r")
  register_metadata_path({ "source", "py" }, "emit.source.py")
  register_metadata_path({ "source", "jl" }, "emit.source.jl", "emit.source.julia")
  if template_vars["source_jl"] ~= nil then
    register_template_path({ "source", "julia" }, template_vars["source_jl"])
  end

  register_metadata_path({ "test", "r" }, "emit.test.r", "emit.tests.r")
  register_metadata_path({ "test", "py" }, "emit.test.py", "emit.tests.py")
  register_metadata_path({ "test", "jl" }, "emit.test.jl", "emit.test.julia", "emit.tests.jl", "emit.tests.julia")
  if template_vars["test_jl"] ~= nil then
    register_template_path({ "test", "julia" }, template_vars["test_jl"])
  end

  register_metadata_path({ "script", "sh" }, "emit.script.sh", "emit.scripts.sh")
  register_metadata_path({ "config", "yaml" }, "emit.config.yaml", "emit.config.yml")
  register_metadata_path({ "config", "json" }, "emit.config.json")
  register_metadata_path({ "config", "toml" }, "emit.config.toml")

  if template_vars["project_root"] == nil then
    register_template_path({ "project_root" }, ".")
  end

  apply_env_override({ "project_root" })
  apply_env_override({ "project_name" })
  apply_env_override({ "source", "r" })
  apply_env_override({ "source", "py" })
  apply_env_override({ "source", "jl" })
  apply_env_override({ "test", "r" })
  apply_env_override({ "test", "py" })
  apply_env_override({ "test", "jl" })
  if template_vars["test_jl"] ~= nil then
    register_template_path({ "test", "julia" }, template_vars["test_jl"])
  end
  apply_env_override({ "script", "sh" })
  apply_env_override({ "config", "yaml" })
  apply_env_override({ "config", "json" })
  apply_env_override({ "config", "toml" })
  if template_vars["source_jl"] ~= nil then
    register_template_path({ "source", "julia" }, template_vars["source_jl"])
  end
end

local function render_template_variables(text)
  return string.gsub(text, "{{%s*([%a_][%w_%.%-]*)%s*}}", function(key)
    return template_vars[key] or "{{ " .. key .. " }}"
  end)
end

local function header_comment(style, source)
  if style == "hash" then
    return "# Generated by quarto-emit.\n"
      .. "# Source: " .. source .. "\n"
      .. "# Do not edit directly unless you intend to stop using this document as the source of truth.\n\n"
  end

  if style == "dash" then
    return "-- Generated by quarto-emit.\n"
      .. "-- Source: " .. source .. "\n"
      .. "-- Do not edit directly unless you intend to stop using this document as the source of truth.\n\n"
  end

  if style == "html" then
    return "<!-- Generated by quarto-emit. -->\n"
      .. "<!-- Source: " .. source .. " -->\n"
      .. "<!-- Do not edit directly unless you intend to stop using this document as the source of truth. -->\n\n"
  end

  if style == "c" then
    return "/* Generated by quarto-emit. */\n"
      .. "/* Source: " .. source .. " */\n"
      .. "/* Do not edit directly unless you intend to stop using this document as the source of truth. */\n\n"
  end

  return ""
end

local function header_for(language, source, target_path)
  local extension = target_path:match("%.([^.]+)$")

  if extension == "json" then
    return ""
  end

  if extension == "md" or extension == "qmd" or extension == "html" or extension == "xml" or extension == "svg" then
    return header_comment("html", source)
  end

  if extension == "css" or extension == "js" or extension == "ts" then
    return header_comment("c", source)
  end

  if language == "lua" or language == "sql" then
    return header_comment("dash", source)
  end

  if language == "markdown" or language == "md" then
    return header_comment("html", source)
  end

  return header_comment("hash", source)
end

local function dirname(path)
  return path:match("(.+)/[^/]+$")
end

local function basename(path)
  return path:match("([^/]+)$") or path
end

local function shell_quote(path)
  return "'" .. string.gsub(path, "'", "'\\''") .. "'"
end

local function mkdir_p(dir)
  if dir ~= nil and dir ~= "" then
    os.execute("mkdir -p " .. shell_quote(dir))
  end
end

local function file_exists(path)
  local handle = io.open(path, "r")
  if handle ~= nil then
    handle:close()
    return true
  end
  return false
end

local function legacy_marker_path(path)
  local dir = dirname(path)
  local base = basename(path)
  if dir == nil or dir == "" then
    return "." .. base .. ".quarto-emit"
  end
  return dir .. "/." .. base .. ".quarto-emit"
end

local function manifest_path()
  local project_root = template_vars["project_root"] or "."
  return project_root .. "/.quarto/quarto-emit-manifest.tsv"
end

local function read_file(path)
  local handle = io.open(path, "r")
  if handle == nil then
    return nil
  end
  local content = handle:read("*a")
  handle:close()
  return content
end

local function has_generated_header(path)
  local content = read_file(path)
  if content == nil then
    return false
  end
  return string.find(content, "Generated by quarto%-emit", 1, false) ~= nil
end

local function read_manifest()
  local manifest = {}
  local handle = io.open(manifest_path(), "r")
  if handle == nil then
    return manifest
  end

  for line in handle:lines() do
    local path, source = line:match("^(.-)\t(.*)$")
    if path ~= nil and path ~= "" then
      manifest[path] = source or ""
    end
  end

  handle:close()
  return manifest
end

local function write_manifest(manifest)
  local path = manifest_path()
  mkdir_p(dirname(path))

  local keys = {}
  for key, _ in pairs(manifest) do
    table.insert(keys, key)
  end
  table.sort(keys)

  local handle = io.open(path, "w")
  if handle == nil then
    error("Could not open manifest for writing: " .. path)
  end

  for _, key in ipairs(keys) do
    handle:write(key .. "\t" .. (manifest[key] or "") .. "\n")
  end

  handle:close()
end

local function remove_file(path)
  local ok, err = os.remove(path)
  if not ok and err ~= nil then
    log_debug("could not remove file " .. path .. ": " .. err)
  end
end

local function has_generated_marker(path)
  local manifest = read_manifest()
  if manifest[path] ~= nil then
    return true
  end

  return file_exists(legacy_marker_path(path))
end

local function write_generated_marker(path, source)
  local manifest = read_manifest()
  manifest[path] = source or ""
  write_manifest(manifest)

  local legacy_path = legacy_marker_path(path)
  if file_exists(legacy_path) then
    remove_file(legacy_path)
  end
end

local function migrate_legacy_marker(path, source)
  local legacy_path = legacy_marker_path(path)
  if file_exists(legacy_path) then
    write_generated_marker(path, source)
  end
end

local function write_file(path, content)
  mkdir_p(dirname(path))
  local handle = io.open(path, "w")
  if handle == nil then
    error("Could not open target for writing: " .. path)
  end
  handle:write(content)
  handle:close()
end

local function chmod_if_requested(path, mode)
  if mode == "0755" then
    os.execute("chmod 0755 " .. shell_quote(path))
  end
end

local function find_emit_class(el)
  local matched = nil

  for class_name, _ in pairs(emit_classes) do
    if el.classes:includes(class_name) then
      quarto.log.output("Checking for emit class: " .. class_name)
      if matched ~= nil then
        error("Emit block must include exactly one emit class.")
      end
      matched = class_name
    end
  end

  return matched
end

local function find_code_blocks(blocks, found)
  found = found or {}

  for _, block in ipairs(blocks) do
    if block.t == "CodeBlock" then
      table.insert(found, block)
    elseif block.content ~= nil then
      find_code_blocks(block.content, found)
    end
  end

  return found
end

local function Header(el)
  el.content = pandoc.Emph(el.content)
  return el
end

local function Div(el)
  local emit_class = find_emit_class(el)
  if emit_class == nil then
    return el
  end

  if os.getenv("QUARTO_EMIT") ~= "1" then
    return el
  end

  local target = el.attributes["file"]
  if target == nil or target == "" then
    error("Emit block is missing file attribute.")
  end

  local code_blocks = find_code_blocks(el.content)
  if #code_blocks ~= 1 then
    error("Emit block must contain exactly one code block: " .. target)
  end

  local code_block = code_blocks[1]
  local source = quarto.doc.input_file or "unknown-source"
  local force = os.getenv("QUARTO_EMIT_FORCE") == "1"
  local check = os.getenv("QUARTO_EMIT_CHECK") == "1"

  local rendered_target = render_template_variables(target)
  local rendered_body = render_template_variables(code_block.text)
  local output = header_for(code_block.classes[1] or "", source, rendered_target) .. rendered_body

  if string.sub(output, -1) ~= "\n" then
    output = output .. "\n"
  end

  local existing = read_file(rendered_target)
  if file_exists(rendered_target) and existing ~= output and not has_generated_header(rendered_target) and not has_generated_marker(rendered_target) and not force then
    error("Refusing to overwrite non-generated file: " .. rendered_target)
  end

  if check then
    if existing == output then
      quarto.log.output("[quarto-emit] unchanged " .. rendered_target)
    else
      quarto.log.output("[quarto-emit] would write " .. rendered_target)
    end
    return el
  end

  if existing ~= output then
    write_file(rendered_target, output)
    write_generated_marker(rendered_target, source)
    chmod_if_requested(rendered_target, el.attributes["mode"])
    quarto.log.output("[quarto-emit] wrote " .. rendered_target)
  else
    migrate_legacy_marker(rendered_target, source)
    quarto.log.output("[quarto-emit] unchanged " .. rendered_target)
  end

  return el
end

return {
  Pandoc = function(doc)
    load_emit_vars()
    return doc:walk({
      Header = Header,
      Div = Div
    })
  end
}
