# this config was migrated from renv.lock on 2026-07-19
[project]
name = "MadagascarWeatherStations"
r_version = "4.5"

repositories = [
    { alias = "CRAN", url = "https://packagemanager.posit.co/cran/latest"}
]

dependencies = [
    { name = "R6", repository = "CRAN" },
    { name = "askpass", repository = "CRAN" },
    { name = "base64enc", repository = "CRAN" },
    { name = "base64url", repository = "CRAN" },
    { name = "bit", repository = "CRAN" },
    { name = "brew", repository = "CRAN" },
    { name = "brio", repository = "CRAN" },
    { name = "cachem", repository = "CRAN" },
    { name = "commonmark", repository = "CRAN" },
    { name = "config", repository = "CRAN" },
    { name = "crayon", repository = "CRAN" },
    { name = "credentials", repository = "CRAN" },
    { name = "desc", repository = "CRAN" },
    { name = "diffobj", repository = "CRAN" },
    { name = "evaluate", repository = "CRAN" },
    { name = "fastmap", repository = "CRAN" },
    { name = "fledge", repository = "CRAN" },
    { name = "fontawesome", repository = "CRAN" },
    { name = "fusen", repository = "CRAN" },
    { name = "generics", repository = "CRAN" },
    { name = "gert", repository = "CRAN" },
    { name = "gitcreds", repository = "CRAN" },
    { name = "here", repository = "CRAN" },
    { name = "hms", repository = "CRAN" },
    { name = "htmlwidgets", repository = "CRAN" },
    { name = "ini", repository = "CRAN" },
    { name = "janitor", repository = "CRAN" },
    { name = "jquerylib", repository = "CRAN" },
    { name = "jsonlite", repository = "CRAN" },
    { name = "knitr", repository = "CRAN" },
    { name = "lifecycle", repository = "CRAN" },
    { name = "lightparser", repository = "CRAN" },
    { name = "lubridate", repository = "CRAN" },
    { name = "memoise", repository = "CRAN" },
    { name = "mime", repository = "CRAN" },
    { name = "miniUI", repository = "CRAN" },
    { name = "pillar", repository = "CRAN" },
    { name = "pkgbuild", repository = "CRAN" },
    { name = "pkgconfig", repository = "CRAN" },
    { name = "praise", repository = "CRAN" },
    { name = "prettyunits", repository = "CRAN" },
    { name = "profvis", repository = "CRAN" },
    { name = "progress", repository = "CRAN" },
    { name = "rcmdcheck", repository = "CRAN" },
    { name = "rematch2", repository = "CRAN" },
    { name = "remotes", repository = "CRAN" },
    { name = "rprojroot", repository = "CRAN" },
    { name = "sass", repository = "CRAN" },
    { name = "snakecase", repository = "CRAN" },
    { name = "stringi", repository = "CRAN" },
    { name = "stringr", repository = "CRAN" },
    { name = "sys", repository = "CRAN" },
    { name = "tarchetypes", git = "https://github.com/ropensci/tarchetypes", commit = "67236fa6644687944fd6ca452e474635f1d71856" },
    { name = "targets", repository = "CRAN" },
    { name = "tibble", repository = "CRAN" },
    { name = "tidyselect", repository = "CRAN" },
    { name = "timechange", repository = "CRAN" },
    { name = "tzdb", repository = "CRAN" },
    { name = "usethis", repository = "CRAN" },
    { name = "utf8", repository = "CRAN" },
    { name = "waldo", repository = "CRAN" },
    { name = "whisker", repository = "CRAN" },
    { name = "whoami", repository = "CRAN" },
    { name = "xopen", repository = "CRAN" },
    { name = "yaml", repository = "CRAN" }
]
