[project]
name = "MadagascarWeatherStations"
description = "Madagascar Weather Stations"

[dependencies]
R6 = "*"
arrow = "*"
askpass = "*"
attachment = "*"
base64enc = "*"
base64url = "*"
bit = "*"
brew = "*"
brio = "*"
cachem = "*"
cli = "*"
commonmark = "*"
config = "*"
crayon = "*"
credentials = "*"
crew = "*"
"crew.cluster" = "*"
desc = "*"
devtools = "*"
diffobj = "*"
dplyr = "*"
evaluate = "*"
fastmap = "*"
fledge = "*"
fontawesome = "*"
fs = "*"
fusen = "*"
generics = "*"
gert = "*"
gitcreds = "*"
gitlabr = "*"
glue = "*"
here = "*"
hms = "*"
htmlwidgets = "*"
httr2 = "*"
igraph = "*"
ini = "*"
janitor = "*"
jquerylib = "*"
jsonlite = "*"
lifecycle = "*"
lightparser = "*"
lubridate = "*"
maestro = "*"
magrittr = "*"
memoise = "*"
mime = "*"
miniUI = "*"
nanoparquet = "*"
pillar = "*"
pkgbuild = "*"
pkgconfig = "*"
pkgdown = "*"
praise = "*"
prettyunits = "*"
profvis = "*"
progress = "*"
purrr = "*"
rcmdcheck = "*"
readr = "*"
readxl = "*"
rematch2 = "*"
remotes = "*"
rprojroot = "*"
sass = "*"
snakecase = "*"
stringi = "*"
stringr = "*"
sys = "*"
tarchetypes = "*"
targets = "*"
tibble = "*"
tidyr = "*"
tidyselect = "*"
timechange = "*"
tzdb = "*"
usethis = "*"
utf8 = "*"
waldo = "*"
whisker = "*"
whoami = "*"
xfun = "*"
xopen = "*"
yaml = "*"

[dependencies.ambientweatheR]
git = "TinasheMTapera/ambientweatheR"
rev = "master"

[dev-dependencies]
ambientweatheR = "*"
knitr = "*"
rmarkdown = "*"
testthat = "*"
